name: 

on:
  push:
    branches: [ workflow-test ]
  pull_request:
    branches: [ workflow-test ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # # Login against a Docker registry except on PR
      # - name: Log into registry ${{ env.REGISTRY }}
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ secrets.REGISTRY_USER }}
      #     password: ${{ secrets.REGISTRY_PASS }}

      # Extract metadata (tags, labels) for Docker
#       - name: Extract Docker metadata
#         id: meta
#         uses: docker/metadata-action@v3
#         with:
#           tags: type=sha
#           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        run: echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::7}
        # uses: docker/build-push-action@v2
        # with:
        #   context: .
        #   push: ${{ github.event_name != 'pull_request' }}
        #   tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::7}

